INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Aro 29 Mountain Bike Endorphine 6.3 - 24 Marchas - Shimano - Alumínio', 8852.00);
INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Altools Stroll Aro 26 Freio À Disco 21 Marchas', 9201.00);
INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Gts Advanced 1.0 Aro 29 Freio Disco Câmbio Traseiro Shimano 24 Marchas', 4255.00);
INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Trinc Câmbios Shimano Aro 29 Freio A Disco 24v', 7658.00);
INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Gometws Endorphine 7.3 - Shimano Alumínio Aro 29 - 24 Marchas', 2966.00);
INSERT INTO produtos(produto, preco) VALUES ('Bicicleta Gometws Endorphine 6.1 Shimano Alumínio- Aro 26 - 21 Marchas', 2955.00);
INSERT INTO produtos(produto, preco) VALUES ('Capacete Gometws Endorphine 2.0', 155.00);
INSERT INTO produtos(produto, preco) VALUES ('Luva De Ciclismo - Gometws Sports', 188.00);
INSERT INTO produtos(produto, preco) VALUES ('Bermuda Predactor 3Xu Pro', 115.00);
INSERT INTO produtos(produto, preco) VALUES ('Camiseta Predactor 3Xu Multiplied', 135.00);