version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: "mongo_container"
    env_file:
    - .env
    ports:
      - 27017:27017
    volumes:
      - ./data/posts.json:/data/db/posts.json
