version: "3"
services:
    jenkins:
      image: pyjenkins
      container_name: "module_jenkins"
      ports:
          - "8000:8080"
          - "50000:50000"
      volumes:
          - "./jenkins_home:/var/jenkins_home"
          - "./cambio:/cambio"
