version: "3"

services:
  postgres:
    image: postgres:13
    container_name: "pg_container"
    env_file:
    - .env
    ports: 
      - "5432:5432"
    volumes:
      - "./db_postgres:/var/lib/postgresql/data/"